[INFO      ] [модуль:              __main__] 2024-03-18 19:27:50,153   - Тестирование логирования
[INFO      ] [модуль:              __main__] 2024-03-18 20:01:48,082   - Запуск скрипта из модуля context_manager (task_1)
[INFO      ] [модуль:task_1.context_manager] 2024-03-18 20:01:48,083   - Указанного файла не существует. В текущей директории был создан и открыт файл: example.txt, режим - w
[INFO      ] [модуль:task_1.context_manager] 2024-03-18 20:01:48,083   - Файл example.txt закрыт
[INFO      ] [модуль:              __main__] 2024-03-18 20:02:48,991   - Запуск скрипта из модуля context_manager (task_1)
[INFO      ] [модуль:task_1.context_manager] 2024-03-18 20:02:48,991   - Файл открыт: example.txt, режим - r
[INFO      ] [модуль:task_1.context_manager] 2024-03-18 20:02:48,992   - Файл example.txt закрыт
[INFO      ] [модуль: task_2.my_math_module] 2024-03-18 21:25:17,491   - Запущена функция вычисления длины окружности circle_len
[INFO      ] [модуль: task_2.my_math_module] 2024-03-18 21:25:17,492   - Функция circle_len отработала корректно
[INFO      ] [модуль: task_2.my_math_module] 2024-03-18 21:25:17,492   - Запущена функция вычисления площади окружности circle_sq
[INFO      ] [модуль: task_2.my_math_module] 2024-03-18 21:25:17,492   - Функция circle_sq отработала корректно
[INFO      ] [модуль:              __main__] 2024-03-18 21:26:32,226   - Запуск скрипта из модуля my_math_module (task_2)
[INFO      ] [модуль: task_2.my_math_module] 2024-03-18 21:26:32,226   - Запущена функция вычисления длины окружности circle_len
[ERROR     ] [модуль: task_2.my_math_module] 2024-03-18 21:26:32,226   - Передано некорректное значение радиуса окружности - five
[INFO      ] [модуль: task_2.my_math_module] 2024-03-18 21:26:32,226   - Запущена функция вычисления площади окружности circle_sq
[INFO      ] [модуль: task_2.my_math_module] 2024-03-18 21:26:32,226   - Функция circle_sq отработала корректно
